### PR TITLE
Fix GitHub enterprise without specifying public tokens

### LINKED ISSUE #143: Broken builds on GitHub Enterprise for bufaction v1.1
Getting build failures on GHE for a previously stable build using `bufaction/buf-action@v1` following the v1.1 release of buf-action 

```
Run bufbuild/buf-action@v1
  with:
    version: 1.40.0
    pr_comment: false
    domain: buf.build
    github_actor: xxxxxxx
    github_token: ***
    setup_only: false
    exclude_imports: false
    lint: true
    format: true
    breaking: true
    push: false
    push_disable_create: false
    archive: false
  env:
    BUF_VERSION: 1.40.0
    GO_VERSION: xxxxxxxxxx
Running on GitHub Enterprise, using public GitHub API.
Warning: public_github_token not set, GitHub API requests may be limited
Error: Parameter token or opts.auth is required
```

Locking to `bufaction/buf-action@v1.0` resolves this issue.

### PR DESCRIPTION
**Pull request by emcfarlane**
This fixes enterprise use of the action when not specifying the parameter `public_github_token`. If the version resolution is not required the action does not need to build the GitHub API client. If it is needed an error explaining the issue is now returned.

Closes #143

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -50,10 +51,12 @@ async function main() {
       core.warning(
         "public_github_token not set, GitHub API requests may be limited",
```
Comment (nicksnyder) [inline src/main.ts:52]: I'm wondering if we should move this warning to only show if we are actually about to make an API request (either in `latestVersion` or `downloadBuf`)? Otherwise we might emit the warning in cases where it doesn't matter (e.g. the user has installed buf some other way, or it is already in the tool cache).

Comment (emcfarlane) [reply src/main.ts]: Moved to `downloadBuf` as that is the only case where a rate limit may apply .

**Review by nicksnyder — APPROVED** [review]

File: src/main.ts (hunk 1 above)
Comment (nicksnyder) [reply src/main.ts]: It seems like rate limits are larger for REST api requests too if you are authed: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users

Comment (emcfarlane) [reply src/main.ts]: On construction of the public REST client we must provide an auth token (based on the user error). So only downloads currently. We may be able to relax this but would need testing. Resolving for now.
